# Generated by Django 6.0.1 on 2026-01-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ANALISADO POR IA', 'Analisado por IA'), ('REVISADO POR HUMANO', 'Revisado por Humano')])),
                ('resultado', models.CharField(choices=[('BENIGNO', 'Benigno'), ('MALIGNO', 'Maligno'), ('SAUDÁVEL', 'Saudável')])),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('CRM', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exame')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
    ]
