# Generated by Django 5.2.8 on 2026-01-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('tipo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('imagem', models.URLField(max_length=30)),
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(help_text='Digite seu nome completo.', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(help_text='Digite apenas o CPF sem pontos ou traços.', max_length=11, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Não informado', 'Não informado')], max_length=20)),
                ('crm', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('especialidade', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=30)),
                ('id_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_do_exame', to='core.exame')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id_laudo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=500, null=True)),
                ('assinatura_medico', models.CharField(max_length=100)),
                ('id_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exame')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo.', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(help_text='Digite apenas o CPF sem pontos ou traços.', max_length=11, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Não informado', 'Não informado')], max_length=20)),
                ('exames_realizados', models.ManyToManyField(through='core.Exame', to='core.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='exames_realizados',
            field=models.ManyToManyField(through='core.Exame', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
    ]
