# Generated by Django 6.0.1 on 2026-01-19 22:50

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='liberado_para_paciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagem',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medico'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='path',
            field=models.ImageField(upload_to=core.models.caminho_upload_exame),
        ),
    ]
