# Generated by Django 6.0.1 on 2026-01-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagem_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='path',
            field=models.ImageField(upload_to='imagens_exames/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogExames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exame')),
            ],
        ),
    ]
