# Generated by Django 5.2.8 on 2026-01-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exame_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='id_exame',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='id_imagem',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='id_exame',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='id_laudo',
        ),
        migrations.AddField(
            model_name='exame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='exame',
            name='laudo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='core.laudo'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='assinatura_medico',
            field=models.CharField(help_text='Assinatura do Médico', max_length=100),
        ),
    ]
