# Generated by Django 6.0.1 on 2026-01-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exame_descricao_exame_liberado_para_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.paciente'),
        ),
    ]
