# Generated by Django 6.0.1 on 2026-01-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='paciente',
        ),
    ]
