# Generated by Django 6.0.1 on 2026-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagem_path_alter_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contato',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
