# Generated by Django 5.2.8 on 2026-01-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exame_id_exame_remove_imagem_id_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='id_exame',
        ),
        migrations.AddField(
            model_name='imagem',
            name='exame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.exame'),
        ),
    ]
